import { NextRequest, NextResponse } from "next/server";
import { supabase } from "@/lib/supabase";
import { OpenAI } from "openai";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export async function POST(req: NextRequest) {
  const { input } = await req.json();

  // Step 1: Get GPT output
  const completion = await openai.chat.completions.create({
    model: "gpt-4.0",
    messages: [
      {
        role: "system",
        content: `You are a productivity assistant. Based on the user's input, extract exactly 3–5 clear, specific, short tasks. Respond ONLY with valid JSON in this format: [{"title": "Step 1"}, {"title": "Step 2"}]. Do not include any explanation.`,
      },
      { role: "user", content: input },
    ],
    temperature: 0.7,
  });

  const raw = completion.choices[0]?.message.content ?? "[]";
  console.log("🔍 GPT raw output:", raw);

  let steps: { title: string }[] = [];
  try {
    steps = JSON.parse(raw);
  } catch (err) {
    console.error("❌ Failed to parse JSON:", err);
    return NextResponse.json({ error: "Invalid JSON from GPT" }, { status: 500 });
  }

  console.log("🧪 Parsed steps:", steps);

  if (steps.length === 0) {
    return NextResponse.json({ error: "No steps generated by GPT" }, { status: 400 });
  }

  // Step 2: Create the Loopz
  const { data: loop, error: loopError } = await supabase
    .from("loopz")
    .insert([{ title: input, description: input, status: "open" }])
    .select()
    .single();

  if (loopError || !loop) {
    console.error("❌ Loop insert error:", loopError);
    return NextResponse.json({ error: loopError?.message || "Loop creation failed" }, { status: 500 });
  }

  // Step 3: Insert Steps
  const stepPayload = steps.map((s) => ({
    loop_id: loop.id,
    title: s.title,
    completed: false,
  }));

  const { error: stepError } = await supabase.from("steps").insert(stepPayload);

  if (stepError) {
    console.error("❌ Step insert error:", stepError);
    return NextResponse.json({ error: "Failed to insert steps" }, { status: 500 });
  }

  return NextResponse.json({ loopId: loop.id });
}